name: Pull Request and Build/Deploy Workflow

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
  push:
    branches:
      - main

jobs:
  clean_commit_job:
    if: github.event_name == 'pull_request'
    name: Prevent Bad Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit Check Action
        uses: commit-check/commit-check-action@v0.7.0
        with:
          # Add configuration options here if required
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Example: set commit message patterns or author requirements

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build index.html file
        run: python build.py

      - name: Upload build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
